----
kind: "pipeline"
name: "lint"

steps:
  - name: "lint"
    image: "golangci/golangci-lint:v1.21.0"
    commands:
      - "cd src && golangci-lint run ."

trigger:
  event:
    include:
    - push
    - pull_request    

---
kind: "pipeline"
name: "test"

steps:
  - name: "test"
    image: "golang:1.13-buster"
    commands:
      - "cd src && go test ./..."

trigger:
  event:
    include:
      - push
      - pull_request
